### ISSUE TITLE
Icon generation updates modified time of the file's folder

### ISSUE THREAD

**Issue by SanokKule** [rejetto/file-icons#5]
Each file from which the icon is grabbed will have the icon saved near it thus updating modified time of the folder.
This messes with [mark-news](https://github.com/rejetto/mark-news) plugin.
Can you change this plugin to store icons in the `storage` folder of the plugin?

Maybe while you at it also keep icons cached there as they are not likely to change?
An option to delete cache might also be useful in that case.

**Comment by rejetto** [comment]
they are cached but the cache is reset at each restart.
I thought this was ok, because it happens rarely.
I'm not sure, maybe you noticed the problem because you worked on it, and had a lot of restarts?

moving the work to storage folder is a bit tricky, as if i keep only the file name i may have collisions, and if preserve the whole path i may have an error because the path is too long.
But I have an idea.

**Comment by rejetto** [comment]
published
LMK

**Comment by SanokKule** [comment]
After a bit of testing, i don't see any problems
